/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package atm;

public class BalanceInquiry extends App
{
    static double balance = 0;
    public void setBalance(double b)
    {
        balance = b;
    }
    public static double getBalance()
    {
        return balance;
    }   
}