/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package testing;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

     public int multiply(int a, int b) {
        return a * b;
    }

    public static void main(String[] args) {
        System.out.println(new App().multiply(10,3));
    }
}
