/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package FunctionalProgramming;

import java.util.ArrayList;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public int sum(int a, int b) {
        return a + b;
    }


    public static void main(String[] args) {
        // System.out.println(new App().sum(3, 5));
        
        ArrayList<String> list = new ArrayList<>();
        list.add("One");
        list.add("Abc");
        list.add("BCD");

        Collections.sort(list, (String a, String b) -> {
            return a.compareTo(b);
        });
         
        System.out.println(list);    

    }
}
