/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package atm;

public class Deposit extends App
{
    static double deposit;
    public void setDeposit(double d)
    {
        deposit = d;
    }
    public static double getDeposit()
    {
        return deposit;
    }
}