/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package classes;

class MountainBike extends Bicycle {

    // new fields and methods defining 
    // a mountain bike would go here

}