/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package classes;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {

    Bicycle classUnderTest = new Bicycle();

    @Test public void testAppHasAGreeting() {
        
        classUnderTest.changeCadence(50);
        classUnderTest.speedUp(10);
        classUnderTest.changeGear(2);
       
        assertEquals(50,classUnderTest.cadence);
    }
}
