/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ReadJson;

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
 
import org.json.simple.JSONArray;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;

public class App
{

    public static void main(String[] args)
    {
        JSONParser jsonparser = new JSONParser();

        try{
            FileReader reader = new FileReader("/D:/belajar/praxis-academy/enterprise-full-stack/novice/01-05/kasusuniversitas.json");

            // Membaca file json
            Object obj = jsonparser.parse(reader);

            JSONArray listuniv = new JSONArray();
            listuniv.add(obj);
            System.out.println(listuniv);
            
        } catch(FileNotFoundException e){
            e.printStackTrace();
        } catch(IOException e){
            e.printStackTrace();
        } catch(ParseException e){
            e.printStackTrace();
        }
    }

}