/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package object;

public class Point {
 public int x = 0;
    public int y = 0;
    //constructor
    public Point(int a, int b) {
        x = a;
        y = b;
    }
}
